### ISSUE TITLE
[BUG] file content of lplug4

### ISSUE THREAD

**Issue by lubeda** [schmic/Loupedeck-HomeAssistant#1]
Hi, your 
lplug4 file is not working.

The loupedeckPackage.yaml and the win/mac-folder also the metadata-folder is missing.

Perhaps you can also change your plugins name a bit like ...WS for websocket or ...NG for next generation to distinguish a bit from my older plugin.

**Comment by EagleDev91** [comment]
Maybe the reason why I'm getting an error on installing the plugin; add-on could not be installed?

**Comment by lubeda** [comment]
Yes, thats the reason

**Comment by pentafive** [comment]
I just tried to install it and the plugin install failed. Happy to help test the next version!

**Comment by schmic** [comment]
0.2 will be broken as well, I just found that issue.
I'll have a look.

**Comment by schmic** [comment]
This is fixed in version v0.3.

Happy to get more feedback.

**Comment by schmic** [comment]
v0.4 has some fixes for the Websocket connection, please try this instead of v0.3
