### ISSUE TITLE
Add ability to update values on any buttons periodically.

### ISSUE THREAD

**Issue by bashers222** [schmic/Loupedeck-HomeAssistant#13]
I understand you are not working on this till the summer, but can you add an ability to set a time to refresh button values.
I've a few buttons with labels that take the current HA values which change over time, but not in Loupedeck, until i restart the app

**Comment by bashers222** [comment]
I've got three buttons that dont do anything other than display various temperatures on a panel on my loupedeck.
As this unit could potentially be used as a powerful HA controller, some buttons may not actually do much but display info
So maybe a setting to poll every minute might be useful, but definitely not in realtime.
However maybe the loupedeck software can't do that kind of timed polling

**Comment by bashers222** [comment]
Either way Michael, I'm really happy where you are with this project and appreciate the effort! :)

**Comment by schmic** [comment]
Thank you for the compliment.

I'd like to know what kind of HA entity you have a button for. Switch, Light, Sensor ...?
Or is it really an HA button entity?

**Comment by bashers222** [comment]
These sensors only so far....
![image](https://github.com/schmic/Loupedeck-HomeAssistant/assets/22331682/27969ce6-29a4-48d8-b5e8-6a14dc3ec79c)

**Comment by schmic** [comment]
So, I'm watching three sesnors with temps over the day and they are instantly updating, either when I manually set a new value in HA or when HA updates them itself. Is this still an issue for you?

**Comment by bashers222** [comment]
Its not broken, just not too aware of network changes.
I drop on and off the work VPN during the day, and occasionally i have to restart loupedeck to reconnect to the nabu casa address.
maybe it could be more aware of a network change?

**Comment by schmic** [comment]
There is a new websocket client implemented from version v0.8 which is aware of connection losses and tries to reconnect, you can check the logfile for information and reconnect efforts. See #8 ...

I tried multiple things which were an issue before like toggling VPN and even restarting HA. Everything works so far. I'm closing this issue, if you keep having connection issue pleae reopen #8 or create a new issue.
